class Static:
    ARTICLETYPE = 'article_type'
    RATING = 'rating'
    BODY = 'body'
    GENRE = 'genre'
    LABEL = 'record_label'
    RELATED = 'related'
    TITLE = 'title'
    AUTHOR = 'author'
    DATEPUBLISHED = 'date_published'